name: Deploy test

on:
  push:
    branches:
      - ting

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.12  
          #https://github.com/actions/setup-node/issues/530

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Verify pnpm Installation
        run: |
          echo "pnpm version:"
          pnpm --version
          echo "PATH:"
          echo $PATH

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
        env:
          DOC_ENV: production
          NODE_OPTIONS: --max-old-space-size=4096
      # 安裝 rsync for act
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync
      - name: Verify build
        run: ls -la .nuxt/dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .nuxt/dist
          force: true
          commit-message: website deploy 
          # The process ‘/usr/bin/git‘ failed with exit code 128  默認權限問題
          # https://blog.csdn.net/weixin_42282187/article/details/124766382


      - name: Cleanup
        if: success()
        run: rm -rf .nuxt/dist
